import{a as b,S as v,i as c}from"./assets/vendor-b11e2a50.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const m of n.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&s(m)}).observe(document,{childList:!0,subtree:!0});function o(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(e){if(e.ep)return;e.ep=!0;const n=o(e);fetch(e.href,n)}})();async function h(t,r,o){try{const s="https://pixabay.com/api/",e="44036260-cc4fe30d806c32d5981005e75";return(await b.get(s,{params:{key:e,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:o}})).data}catch(s){throw console.error("Error fetching images:",s),s}}const i=document.querySelector(".gallery"),L=new v(".gallery a",{captionsData:"alt",captionDelay:250});L.refresh();function E(t,r){let o=t.reduce((s,e)=>s+`
      <li class="gallery-item">
        <a href="${e.largeImageURL}" class="gallery-link">
          <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-img">
          <ul class="gallery-descript">
    <li class="gallery-descript__item"><p><span class="gallery-descript__span">Likes</span>${e.likes}</p></li>
  <li class="gallery-descript__item"><p><span class="gallery-descript__span">Views</span>${e.views}</p></li>
  <li class="gallery-descript__item"><p><span class="gallery-descript__span">Comments</span>${e.comments}</p></li>
  <li class="gallery-descript__item"><p><span class="gallery-descript__span">Downloads</span>${e.downloads}</p></li>
        </ul>
        </a>
      </li>
    `,"");r&&(o+=`<p class="end-message">We're sorry, but you've reached the end of search results.</p>`),i.insertAdjacentHTML("beforeend",o),L.refresh()}const S=document.querySelector(".search-form"),y=document.querySelector(".search-input"),w=document.querySelector(".loader"),u=document.querySelector(".load-more-btn"),f=document.querySelector(".scroll-to-top");function T(){w.classList.remove("is-hidden")}function g(){w.classList.add("is-hidden")}g();let d="",l=1;const a=15;S.addEventListener("submit",M);async function M(t){if(t.preventDefault(),d=y.value.trim(),l=1,i.innerHTML="",d===""){c.error({title:"Error",message:"Please complete the field.",position:"topCenter"}),p();return}C(),T();try{const r=await h(d,l,a),o=r.totalHits;if(r.hits.length===0){i.innerHTML="",c.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),p();return}else{const s=a*l>=o;E(r.hits,s),y.value="",s||q()}a*l>=o&&(p(),_())}catch(r){console.error("Error fetching images:",r),c.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topCenter"})}finally{g()}}u.addEventListener("click",async()=>{try{u&&(l+=1);const t=await h(d,l,a),r=t.totalHits,o=a*l>=r;E(t.hits,o),o&&(p(),_());const s=i.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:s*3,behavior:"smooth"})}catch(t){console.error("Error fetching more images:",t),c.error({title:"Error",message:`Error fetching more images: ${t}`})}finally{g()}});function q(){u.style.display="block"}function p(){u.style.display="none"}function C(){const t=document.querySelector(".end-message");t&&t.remove()}function _(){if(!document.querySelector(".end-message")){const t=document.createElement("p");t.classList.add("end-message"),t.textContent="We're sorry, but you've reached the end of search results.",i.insertAdjacentElement("beforeend",t)}}window.addEventListener("scroll",()=>{document.body.scrollTop>30||document.documentElement.scrollTop>30?f.style.display="flex":f.style.display="none"});function H(){window.scrollTo({top:0,behavior:"smooth"})}f.addEventListener("click",H);
//# sourceMappingURL=commonHelpers.js.map
