import{a as b,S as v,i}from"./assets/vendor-b11e2a50.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const m of s.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&l(m)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();async function h(t,r,o){try{const l="https://pixabay.com/api/",e="44036260-cc4fe30d806c32d5981005e75";return(await b.get(l,{params:{key:e,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:o}})).data}catch(l){throw console.error("Error fetching images:",l),l}}const d=document.querySelector(".gallery"),L=new v(".gallery a",{captionsData:"alt",captionDelay:250});L.refresh();function w(t,r){let o=t.reduce((l,e)=>l+`
      <li class="gallery-item">
        <a href="${e.largeImageURL}" class="gallery-link">
          <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-img">
          <ul class="gallery-descript">
    <li class="gallery-descript__item"><p><span class="gallery-descript__span">Likes</span>${e.likes}</p></li>
  <li class="gallery-descript__item"><p><span class="gallery-descript__span">Views</span>${e.views}</p></li>
  <li class="gallery-descript__item"><p><span class="gallery-descript__span">Comments</span>${e.comments}</p></li>
  <li class="gallery-descript__item"><p><span class="gallery-descript__span">Downloads</span>${e.downloads}</p></li>
        </ul>
        </a>
      </li>
    `,"");r&&(o+=`<p class="end-message">We're sorry, but you've reached the end of search results.</p>`),d.insertAdjacentHTML("beforeend",o),L.refresh()}const T=document.querySelector(".search-form"),g=document.querySelector(".search-input"),E=document.querySelector(".loader"),p=document.querySelector(".load-more-btn"),f=document.querySelector(".scroll-to-top");function _(){E.classList.remove("is-hidden")}function y(){E.classList.add("is-hidden")}y();let a="",n=1;const u=15;T.addEventListener("submit",M);async function M(t){if(t.preventDefault(),a=g.value.trim(),n=1,d.innerHTML="",a===""){i.error({title:"Error",message:"Please complete the field.",position:"topCenter"}),c();return}q(),_();try{const r=await h(a,n,u),o=r.totalHits;if(r.hits.length===0){d.innerHTML="",i.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),c();return}else w(r.hits),g.value="",S();u*n>=o&&(c(),showEndOfCollectionMessage())}catch(r){console.error("Error fetching images:",r),i.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topCenter"})}finally{y()}}p.addEventListener("click",async()=>{try{p&&(n+=1);const t=await h(a,n,u),r=t.totalHits;w(t.hits),_(),u*n>=r&&(c(),showEndOfCollectionMessage());const o=d.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:o*3,behavior:"smooth"})}catch(t){console.error("Error fetching more images:",t),i.error({title:"Error",message:`Error fetching more images: ${t}`})}finally{y()}});function S(){p.style.display="block"}function c(){p.style.display="none"}function q(){const t=document.querySelector(".end-message");t&&t.remove()}window.addEventListener("scroll",()=>{document.body.scrollTop>30||document.documentElement.scrollTop>30?f.style.display="flex":f.style.display="none"});function C(){window.scrollTo({top:0,behavior:"smooth"})}f.addEventListener("click",C);
//# sourceMappingURL=commonHelpers.js.map
